<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributesTableSeeder extends Seeder
{
    public function run()
    {
        $attributes = [
            [
                'id' => 19,
                'code' => 'title',
                'name' => 'Title',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'initiatives',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 20,
                'code' => 'description',
                'name' => 'Description',
                'type' => 'textarea',
                'lookup_type' => NULL,
                'entity_type' => 'initiatives',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 21,
                'code' => 'initiative_value',
                'name' => 'Value',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'initiatives',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 22,
                'code' => 'initiative_source_id',
                'name' => 'Source',
                'type' => 'select',
                'lookup_type' => 'initiative_sources',
                'entity_type' => 'initiatives',
                'sort_order' => 4,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 23,
                'code' => 'initiative_type_id',
                'name' => 'Type',
                'type' => 'select',
                'lookup_type' => 'initiative_types',
                'entity_type' => 'initiatives',
                'sort_order' => 5,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 24,
                'code' => 'user_id',
                'name' => 'Owner',
                'type' => 'select',
                'lookup_type' => 'users',
                'entity_type' => 'initiatives',
                'sort_order' => 7,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 25,
                'code' => 'expected_close_date',
                'name' => 'Projected Outcome Date',
                'type' => 'date',
                'lookup_type' => NULL,
                'entity_type' => 'initiatives',
                'sort_order' => 8,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 26,
                'code' => 'initiative_pipeline_id',
                'name' => 'Pipeline',
                'type' => 'lookup',
                'lookup_type' => 'initiative_pipelines',
                'entity_type' => 'initiatives',
                'sort_order' => 9,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 27,
                'code' => 'initiative_pipeline_stage_id',
                'name' => 'Stage',
                'type' => 'lookup',
                'lookup_type' => 'initiative_pipeline_stages',
                'entity_type' => 'initiatives',
                'sort_order' => 10,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 28,
                'code' => 'name',
                'name' => 'Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'persons',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 29,
                'code' => 'emails',
                'name' => 'Emails',
                'type' => 'email',
                'lookup_type' => NULL,
                'entity_type' => 'persons',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 30,
                'code' => 'contact_numbers',
                'name' => 'Contact Numbers',
                'type' => 'phone',
                'lookup_type' => NULL,
                'entity_type' => 'persons',
                'sort_order' => 3,
                'validation' => 'numeric',
                'is_required' => 0,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 31,
                'code' => 'job_title',
                'name' => 'Job Title',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'persons',
                'sort_order' => 4,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 32,
                'code' => 'user_id',
                'name' => 'Owner',
                'type' => 'lookup',
                'lookup_type' => 'users',
                'entity_type' => 'persons',
                'sort_order' => 5,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 33,
                'code' => 'organization_id',
                'name' => 'Organization',
                'type' => 'lookup',
                'lookup_type' => 'organizations',
                'entity_type' => 'persons',
                'sort_order' => 6,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 34,
                'code' => 'name',
                'name' => 'Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'organizations',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 35,
                'code' => 'address',
                'name' => 'Address',
                'type' => 'address',
                'lookup_type' => NULL,
                'entity_type' => 'organizations',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 36,
                'code' => 'user_id',
                'name' => 'Owner',
                'type' => 'lookup',
                'lookup_type' => 'users',
                'entity_type' => 'organizations',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 37,
                'code' => 'name',
                'name' => 'Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 38,
                'code' => 'description',
                'name' => 'Description',
                'type' => 'textarea',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 39,
                'code' => 'sku',
                'name' => 'SKU',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 40,
                'code' => 'quantity',
                'name' => 'Quantity',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 4,
                'validation' => 'numeric',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 41,
                'code' => 'price',
                'name' => 'Price',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 5,
                'validation' => 'decimal',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 42,
                'code' => 'user_id',
                'name' => 'Owner',
                'type' => 'select',
                'lookup_type' => 'users',
                'entity_type' => 'quotes',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 43,
                'code' => 'subject',
                'name' => 'Subject',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 44,
                'code' => 'description',
                'name' => 'Description',
                'type' => 'textarea',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 45,
                'code' => 'billing_address',
                'name' => 'Billing Address',
                'type' => 'address',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 4,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 46,
                'code' => 'shipping_address',
                'name' => 'Shipping Address',
                'type' => 'address',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 5,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 47,
                'code' => 'discount_percent',
                'name' => 'Discount Percent',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 6,
                'validation' => 'decimal',
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 48,
                'code' => 'discount_amount',
                'name' => 'Discount Amount',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 7,
                'validation' => 'decimal',
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 49,
                'code' => 'tax_amount',
                'name' => 'Tax Amount',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 8,
                'validation' => 'decimal',
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 50,
                'code' => 'adjustment_amount',
                'name' => 'Adjustment Amount',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 9,
                'validation' => 'decimal',
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 51,
                'code' => 'sub_total',
                'name' => 'Sub Total',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 10,
                'validation' => 'decimal',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 52,
                'code' => 'grand_total',
                'name' => 'Grand Total',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 11,
                'validation' => 'decimal',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 53,
                'code' => 'expired_at',
                'name' => 'Expired At',
                'type' => 'date',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 12,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 54,
                'code' => 'person_id',
                'name' => 'Person',
                'type' => 'lookup',
                'lookup_type' => 'persons',
                'entity_type' => 'quotes',
                'sort_order' => 13,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 55,
                'code' => 'name',
                'name' => 'Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 56,
                'code' => 'description',
                'name' => 'Description',
                'type' => 'textarea',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 57,
                'code' => 'contact_name',
                'name' => 'Contact Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 58,
                'code' => 'contact_emails',
                'name' => 'Contact Emails',
                'type' => 'email',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 4,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 59,
                'code' => 'contact_numbers',
                'name' => 'Contact Numbers',
                'type' => 'phone',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 5,
                'validation' => 'numeric',
                'is_required' => 0,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
            [
                'id' => 60,
                'code' => 'contact_address',
                'name' => 'Contact Address',
                'type' => 'address',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 6,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ],
        ];

        $billFileAttributes = [
            [
                'id' => 61,
                'code' => 'billid',
                'name' => 'Bill ID',
                'type' => 'text',
                'lookup_type' => null,
                'entity_type' => 'bill_files',
                'sort_order' => 1,
                'validation' => null,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'code' => 'billname',
                'name' => 'Bill Name',
                'type' => 'text',
                'lookup_type' => null,
                'entity_type' => 'bill_files',
                'sort_order' => 2,
                'validation' => null,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        $attributes = array_merge($attributes, $billFileAttributes);

        foreach ($attributes as $attribute) {
            try {
                DB::table('attributes')->updateOrInsert(
                    [
                        'code' => $attribute['code'],
                        'entity_type' => $attribute['entity_type']
                    ],
                    $attribute
                );
            } catch (\Illuminate\Database\QueryException $e) {
                // If there's a duplicate entry, we'll update the existing record
                if ($e->errorInfo[1] == 1062) {
                    DB::table('attributes')
                        ->where('code', $attribute['code'])
                        ->where('entity_type', $attribute['entity_type'])
                        ->update($attribute);
                } else {
                    // If it's not a duplicate entry error, we'll rethrow the exception
                    throw $e;
                }
            }
        }
    }
}