<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AttributesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('attributes')->delete();
        
        \DB::table('attributes')->insert(array (
            0 => 
            array (
                'id' => 19,
                'code' => 'title',
                'name' => 'Title',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'leads',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            1 => 
            array (
                'id' => 20,
                'code' => 'description',
                'name' => 'Description',
                'type' => 'textarea',
                'lookup_type' => NULL,
                'entity_type' => 'leads',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            2 => 
            array (
                'id' => 21,
                'code' => 'lead_value',
                'name' => 'Lead Value',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'leads',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            3 => 
            array (
                'id' => 22,
                'code' => 'lead_source_id',
                'name' => 'Source',
                'type' => 'select',
                'lookup_type' => 'lead_sources',
                'entity_type' => 'leads',
                'sort_order' => 4,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            4 => 
            array (
                'id' => 23,
                'code' => 'lead_type_id',
                'name' => 'Type',
                'type' => 'select',
                'lookup_type' => 'lead_types',
                'entity_type' => 'leads',
                'sort_order' => 5,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            5 => 
            array (
                'id' => 24,
                'code' => 'user_id',
                'name' => 'Sales Owner',
                'type' => 'select',
                'lookup_type' => 'users',
                'entity_type' => 'leads',
                'sort_order' => 7,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            6 => 
            array (
                'id' => 25,
                'code' => 'expected_close_date',
                'name' => 'Expected Close Date',
                'type' => 'date',
                'lookup_type' => NULL,
                'entity_type' => 'leads',
                'sort_order' => 8,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            7 => 
            array (
                'id' => 26,
                'code' => 'lead_pipeline_id',
                'name' => 'Pipeline',
                'type' => 'lookup',
                'lookup_type' => 'lead_pipelines',
                'entity_type' => 'leads',
                'sort_order' => 9,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            8 => 
            array (
                'id' => 27,
                'code' => 'lead_pipeline_stage_id',
                'name' => 'Stage',
                'type' => 'lookup',
                'lookup_type' => 'lead_pipeline_stages',
                'entity_type' => 'leads',
                'sort_order' => 10,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            9 => 
            array (
                'id' => 28,
                'code' => 'name',
                'name' => 'Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'persons',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            10 => 
            array (
                'id' => 29,
                'code' => 'emails',
                'name' => 'Emails',
                'type' => 'email',
                'lookup_type' => NULL,
                'entity_type' => 'persons',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            11 => 
            array (
                'id' => 30,
                'code' => 'contact_numbers',
                'name' => 'Contact Numbers',
                'type' => 'phone',
                'lookup_type' => NULL,
                'entity_type' => 'persons',
                'sort_order' => 3,
                'validation' => 'numeric',
                'is_required' => 0,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            12 => 
            array (
                'id' => 31,
                'code' => 'job_title',
                'name' => 'Job Title',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'persons',
                'sort_order' => 4,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            13 => 
            array (
                'id' => 32,
                'code' => 'user_id',
                'name' => 'Sales Owner',
                'type' => 'lookup',
                'lookup_type' => 'users',
                'entity_type' => 'persons',
                'sort_order' => 5,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            14 => 
            array (
                'id' => 33,
                'code' => 'organization_id',
                'name' => 'Organization',
                'type' => 'lookup',
                'lookup_type' => 'organizations',
                'entity_type' => 'persons',
                'sort_order' => 6,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            15 => 
            array (
                'id' => 34,
                'code' => 'name',
                'name' => 'Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'organizations',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            16 => 
            array (
                'id' => 35,
                'code' => 'address',
                'name' => 'Address',
                'type' => 'address',
                'lookup_type' => NULL,
                'entity_type' => 'organizations',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            17 => 
            array (
                'id' => 36,
                'code' => 'user_id',
                'name' => 'Sales Owner',
                'type' => 'lookup',
                'lookup_type' => 'users',
                'entity_type' => 'organizations',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            18 => 
            array (
                'id' => 37,
                'code' => 'name',
                'name' => 'Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            19 => 
            array (
                'id' => 38,
                'code' => 'description',
                'name' => 'Description',
                'type' => 'textarea',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            20 => 
            array (
                'id' => 39,
                'code' => 'sku',
                'name' => 'SKU',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            21 => 
            array (
                'id' => 40,
                'code' => 'quantity',
                'name' => 'Quantity',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 4,
                'validation' => 'numeric',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            22 => 
            array (
                'id' => 41,
                'code' => 'price',
                'name' => 'Price',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'products',
                'sort_order' => 5,
                'validation' => 'decimal',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            23 => 
            array (
                'id' => 42,
                'code' => 'user_id',
                'name' => 'Sales Owner',
                'type' => 'select',
                'lookup_type' => 'users',
                'entity_type' => 'quotes',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            24 => 
            array (
                'id' => 43,
                'code' => 'subject',
                'name' => 'Subject',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            25 => 
            array (
                'id' => 44,
                'code' => 'description',
                'name' => 'Description',
                'type' => 'textarea',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            26 => 
            array (
                'id' => 45,
                'code' => 'billing_address',
                'name' => 'Billing Address',
                'type' => 'address',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 4,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            27 => 
            array (
                'id' => 46,
                'code' => 'shipping_address',
                'name' => 'Shipping Address',
                'type' => 'address',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 5,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            28 => 
            array (
                'id' => 47,
                'code' => 'discount_percent',
                'name' => 'Discount Percent',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 6,
                'validation' => 'decimal',
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            29 => 
            array (
                'id' => 48,
                'code' => 'discount_amount',
                'name' => 'Discount Amount',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 7,
                'validation' => 'decimal',
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            30 => 
            array (
                'id' => 49,
                'code' => 'tax_amount',
                'name' => 'Tax Amount',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 8,
                'validation' => 'decimal',
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            31 => 
            array (
                'id' => 50,
                'code' => 'adjustment_amount',
                'name' => 'Adjustment Amount',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 9,
                'validation' => 'decimal',
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            32 => 
            array (
                'id' => 51,
                'code' => 'sub_total',
                'name' => 'Sub Total',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 10,
                'validation' => 'decimal',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            33 => 
            array (
                'id' => 52,
                'code' => 'grand_total',
                'name' => 'Grand Total',
                'type' => 'price',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 11,
                'validation' => 'decimal',
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            34 => 
            array (
                'id' => 53,
                'code' => 'expired_at',
                'name' => 'Expired At',
                'type' => 'date',
                'lookup_type' => NULL,
                'entity_type' => 'quotes',
                'sort_order' => 12,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            35 => 
            array (
                'id' => 54,
                'code' => 'person_id',
                'name' => 'Person',
                'type' => 'lookup',
                'lookup_type' => 'persons',
                'entity_type' => 'quotes',
                'sort_order' => 13,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            36 => 
            array (
                'id' => 55,
                'code' => 'name',
                'name' => 'Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 1,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            37 => 
            array (
                'id' => 56,
                'code' => 'description',
                'name' => 'Description',
                'type' => 'textarea',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 2,
                'validation' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            38 => 
            array (
                'id' => 57,
                'code' => 'contact_name',
                'name' => 'Contact Name',
                'type' => 'text',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 3,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            39 => 
            array (
                'id' => 58,
                'code' => 'contact_emails',
                'name' => 'Contact Emails',
                'type' => 'email',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 4,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            40 => 
            array (
                'id' => 59,
                'code' => 'contact_numbers',
                'name' => 'Contact Numbers',
                'type' => 'phone',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 5,
                'validation' => 'numeric',
                'is_required' => 0,
                'is_unique' => 1,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
            41 => 
            array (
                'id' => 60,
                'code' => 'contact_address',
                'name' => 'Contact Address',
                'type' => 'address',
                'lookup_type' => NULL,
                'entity_type' => 'warehouses',
                'sort_order' => 6,
                'validation' => NULL,
                'is_required' => 1,
                'is_unique' => 0,
                'quick_add' => 1,
                'is_user_defined' => 0,
                'created_at' => '2024-10-01 08:36:21',
                'updated_at' => '2024-10-01 08:36:21',
            ),
        ));
        
        
    }
}